config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  root :to=>"home#index"

  resources :veiculos
  resources :filiais
  resources :empresas

end

app/models/empresa.rb
class Empresa < ActiveRecord::Base
end

app/models/filial.rb
class Filial < ActiveRecord::Base
  belongs_to :empresa
end

app/models/veiculo.rb
class Veiculo < ActiveRecord::Base
  belongs_to :empresa
  belongs_to :filial
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/empresas_controller.rb
class EmpresasController < ApplicationController
  before_action :set_empresa, only: [:show, :edit, :update, :destroy]

  # GET /empresas
  # GET /empresas.json
  def index
    @empresas = Empresa.all
  end

  # GET /empresas/1
  # GET /empresas/1.json
  def show
  end

  # GET /empresas/new
  def new
    @empresa = Empresa.new
  end

  # GET /empresas/1/edit
  def edit
  end

  # POST /empresas
  # POST /empresas.json
  def create
    @empresa = Empresa.new(empresa_params)

    respond_to do |format|
      if @empresa.save
        format.html { redirect_to @empresa, notice: 'Empresa was successfully created.' }
        format.json { render :show, status: :created, location: @empresa }
      else
        format.html { render :new }
        format.json { render json: @empresa.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /empresas/1
  # PATCH/PUT /empresas/1.json
  def update
    respond_to do |format|
      if @empresa.update(empresa_params)
        format.html { redirect_to @empresa, notice: 'Empresa was successfully updated.' }
        format.json { render :show, status: :ok, location: @empresa }
      else
        format.html { render :edit }
        format.json { render json: @empresa.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /empresas/1
  # DELETE /empresas/1.json
  def destroy
    @empresa.destroy
    respond_to do |format|
      format.html { redirect_to empresas_url, notice: 'Empresa was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_empresa
      @empresa = Empresa.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def empresa_params
      params.require(:empresa).permit(:nome, :endereco, :cnpj)
    end
end

app/controllers/filiais_controller.rb
class FiliaisController < ApplicationController
  before_action :set_filial, only: [:show, :edit, :update, :destroy]

  # GET /filiais
  # GET /filiais.json
  def index
    @filiais = Filial.all
  end

  # GET /filiais/1
  # GET /filiais/1.json
  def show
  end

  # GET /filiais/new
  def new
    @filial = Filial.new
  end

  # GET /filiais/1/edit
  def edit
  end

  # POST /filiais
  # POST /filiais.json
  def create
    @filial = Filial.new(filial_params)

    respond_to do |format|
      if @filial.save
        format.html { redirect_to @filial, notice: 'Filial was successfully created.' }
        format.json { render :show, status: :created, location: @filial }
      else
        format.html { render :new }
        format.json { render json: @filial.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /filiais/1
  # PATCH/PUT /filiais/1.json
  def update
    respond_to do |format|
      if @filial.update(filial_params)
        format.html { redirect_to @filial, notice: 'Filial was successfully updated.' }
        format.json { render :show, status: :ok, location: @filial }
      else
        format.html { render :edit }
        format.json { render json: @filial.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /filiais/1
  # DELETE /filiais/1.json
  def destroy
    @filial.destroy
    respond_to do |format|
      format.html { redirect_to filiais_url, notice: 'Filial was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_filial
      @filial = Filial.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def filial_params
      params.require(:filial).permit(:nome, :endereco, :cnpj, :empresa_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/veiculos_controller.rb
class VeiculosController < ApplicationController
  before_action :set_veiculo, only: [:show, :edit, :update, :destroy]

  # GET /veiculos
  # GET /veiculos.json
  def index
    @veiculos = Veiculo.all
  end

  # GET /veiculos/1
  # GET /veiculos/1.json
  def show
  end

  # GET /veiculos/new
  def new
    @veiculo = Veiculo.new
  end

  # GET /veiculos/1/edit
  def edit
  end

  # POST /veiculos
  # POST /veiculos.json
  def create
    @veiculo = Veiculo.new(veiculo_params)

    respond_to do |format|
      if @veiculo.save
        format.html { redirect_to @veiculo, notice: 'Veiculo was successfully created.' }
        format.json { render :show, status: :created, location: @veiculo }
      else
        format.html { render :new }
        format.json { render json: @veiculo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /veiculos/1
  # PATCH/PUT /veiculos/1.json
  def update
    respond_to do |format|
      if @veiculo.update(veiculo_params)
        format.html { redirect_to @veiculo, notice: 'Veiculo was successfully updated.' }
        format.json { render :show, status: :ok, location: @veiculo }
      else
        format.html { render :edit }
        format.json { render json: @veiculo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /veiculos/1
  # DELETE /veiculos/1.json
  def destroy
    @veiculo.destroy
    respond_to do |format|
      format.html { redirect_to veiculos_url, notice: 'Veiculo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_veiculo
      @veiculo = Veiculo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def veiculo_params
      params.require(:veiculo).permit(:empresa_id, :filial_id, :placa, :ano, :numero, :renavam)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/empresas_helper.rb
module EmpresasHelper
end

app/helpers/filiais_helper.rb
module FiliaisHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/veiculos_helper.rb
module VeiculosHelper
end

app/views/empresas/_form.html.haml
= simple_form_for(@empresa) do |f|
  = f.error_notification

  .form-inputs
    = f.input :nome
    = f.input :endereco, label: "Endereço"
    = f.input :cnpj


  .form-actions
    = f.submit "Salvar"

app/views/empresas/edit.html.haml
%h1 Editing empresa

= render 'form'

= link_to 'Show', @empresa
\|
= link_to 'Back', empresas_path

app/views/empresas/index.html.haml
%h1 Listing empresas

%table
  %tr
    %th Nome
    %th Endereco
    %th Cnpj
    %th
    %th
    %th

  - @empresas.each do |empresa|
    %tr
      %td= empresa.nome
      %td= empresa.endereco
      %td= empresa.cnpj
      %td= link_to 'Show', empresa
      %td= link_to 'Edit', edit_empresa_path(empresa)
      %td= link_to 'Excluir', empresa, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Empresa', new_empresa_path

app/views/empresas/new.html.haml
%h1 New empresa

= render 'form'

= link_to 'Back', empresas_path

app/views/empresas/show.html.haml
%p#notice= notice

%p
  %b Nome:
  = @empresa.nome
%p
  %b Endereço:
  = @empresa.endereco
%p
  %b Cnpj:
  = @empresa.cnpj

= link_to 'Edit', edit_empresa_path(@empresa)
\|
= link_to 'Back', empresas_path

app/views/filiais/_form.html.haml
= simple_form_for(@filial) do |f|
  = f.error_notification

  .form-inputs
    = f.input :nome 
    = f.input :endereco, label: "Endereço"
    = f.input :cnpj 
    = f.association :empresa, label_method: :nome

  .form-actions
    = f.submit "Salvar"

app/views/filiais/edit.html.haml
%h1 Editing filial

= render 'form'

= link_to 'Show', @filial
\|
= link_to 'Back', filiais_path

app/views/filiais/index.html.haml
%h1 Listing filiais

%table
  %tr
    %th Nome
    %th Endereco
    %th Cnpj
    %th Empresa
    %th
    %th
    %th

  - @filiais.each do |filial|
    %tr
      %td= filial.nome
      %td= filial.endereco
      %td= filial.cnpj
      %td= filial.empresa
      %td= link_to 'Show', filial
      %td= link_to 'Edit', edit_filial_path(filial)
      %td= link_to 'Excluir', filial, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Filial', new_filial_path

app/views/filiais/new.html.haml
%h1 New filial

= render 'form'

= link_to 'Back', filiais_path

app/views/filiais/show.html.haml
%p#notice= notice

%p
  %b Nome:
  = @filial.nome
%p
  %b Endereço:
  = @filial.endereco
%p
  %b Cnpj:
  = @filial.cnpj
%p
  %b Empresa:
  = @filial.empresa.nome

= link_to 'Edit', edit_filial_path(@filial)
\|
= link_to 'Back', filiais_path

app/views/home/index.html.haml
%h1 Sistema de Venda 
%p Sistema de Venda de Veiculos

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!--
Design by Free CSS Templates
http://www.freecsstemplates.org
Released for free under a Creative Commons Attribution 2.5 License
Name     : Regeneracy
Description: A two-column, fixed-width design with dark color scheme.
Version : 1.0
Released   : 20100529
-->
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta name="keywords" content="" />
<meta name="description" content="" />
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<title>Sistema de Veiculos</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :application %>
  <%= csrf_meta_tag %>
</head>
<body>
<div id='wrapper'>
  <div id='header-wrapper'>
    <div id='header'>
      <div id='logo'>
        <h1><a href='/'>Sistema de Veíciluos</a></h1>
                                
      </div>
         <div id = 'menu'>
            <ul>
              <li><%= link_to 'Empresa',empresas_path %></li>
              <li><%= link_to 'Filial',filiais_path %></li>
             <li><%= link_to 'Veiculo',veiculos_path %></li>
             


            </ul>
         </div>
                </div>
           </div>
     <div id='page'>

       <div id='page-bgtop'>
        <div id='page-bgbtm'>
        <%= yield %>
          <div style='clear: both;'> </div>
        </div>
      </div>

     </div>

 </div>
</body>
</html>

app/views/veiculos/_form.html.haml
= simple_form_for(@veiculo) do |f|
  = f.error_notification

  .form-inputs
    = f.association :empresa, label_method: :nome
    = f.association :filial, label_method: :nome
    = f.input :placa
    = f.input :ano
    = f.input :numero
    = f.input :renavam

  .form-actions
    = f.submit "Salvar"

app/views/veiculos/edit.html.haml
%h1 Editing veiculo

= render 'form'

= link_to 'Show', @veiculo
\|
= link_to 'Back', veiculos_path

app/views/veiculos/index.html.haml
%h1 Listing veiculos

%table
  %tr
    %th Empresa
    %th Filial
    %th Placa
    %th Ano
    %th Numero
    %th Renavam
    %th
    %th
    %th

  - @veiculos.each do |veiculo|
    %tr
      %td= veiculo.empresa.nome
      %td= veiculo.filial.nome
      %td= veiculo.placa
      %td= veiculo.ano
      %td= veiculo.numero
      %td= veiculo.renavam
      %td= link_to 'Show', veiculo
      %td= link_to 'Edit', edit_veiculo_path(veiculo)
      %td= link_to 'Excluir', veiculo, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Veiculo', new_veiculo_path

app/views/veiculos/new.html.haml
%h1 New veiculo

= render 'form'

= link_to 'Back', veiculos_path

app/views/veiculos/show.html.haml
%p#notice= notice

%p
  %b Empresa:
  = @veiculo.empresa.nome
%p
  %b Filial:
  = @veiculo.filial.nome
%p
  %b Placa:
  = @veiculo.placa
%p
  %b Ano:
  = @veiculo.ano
%p
  %b Numero:
  = @veiculo.numero
%p
  %b Renavam:
  = @veiculo.renavam

= link_to 'Edit', edit_veiculo_path(@veiculo)
\|
= link_to 'Back', veiculos_path